from __future__ import annotations

import json
import math
import os
from pathlib import Path
from typing import Iterable, List, Sequence, Tuple, Dict, Any

import numpy as np
import shapely
from shapely import affinity
from shapely.geometry import Point, Polygon, MultiPolygon, GeometryCollection, box, LineString
from shapely.ops import unary_union
import trimesh

SCRIPT_DIR = Path(__file__).resolve().parent
# When this source file is run from the packaged SOURCE directory, regenerate
# into SOURCE/_regenerated by default. During the original build, generate next
# to this script. Set ACOUSTIC_ENCODER_OUTPUT to override either behavior.
DEFAULT_ROOT = (SCRIPT_DIR / '_regenerated') if SCRIPT_DIR.name == 'SOURCE' else SCRIPT_DIR
ROOT = Path(os.environ.get('ACOUSTIC_ENCODER_BUILD_ROOT', DEFAULT_ROOT))
OUT = Path(os.environ.get('ACOUSTIC_ENCODER_OUTPUT', ROOT / 'Acoustic_Morphology_Encoder_V1'))
STL = OUT / 'STL'
SRC = OUT / 'SOURCE'
DOC = OUT / 'DOCS'
SVG = OUT / 'TEMPLATES'
PREV = OUT / 'PREVIEWS'
for d in [OUT, STL, SRC, DOC, SVG, PREV]:
    d.mkdir(parents=True, exist_ok=True)

# -----------------------------
# Global parameters (millimetres)
# -----------------------------
P: Dict[str, Any] = {
    'version': '1.0.1',
    'coordinate_system': 'mm; acoustic head center=(0,0); +Y=N, +X=E; base bottom z=0',
    'printer_bed_target_mm': [220, 220],
    'head': {
        'overall_span_mm': 210.0,
        'arm_half_width_mm': 27.0,
        'center_outer_radius_mm': 50.0,
        'base_floor_mm': 2.4,
        'base_total_height_mm': 10.4,
        'lid_thickness_mm': 3.0,
        'central_chamber_radius_mm': 18.0,
        'fixed_channel_width_mm': 9.0,
        'fixed_channel_height_mm': 8.0,
        'port_nominal_opening_mm': [15.0, 8.0],
    },
    'module': {
        'body_length_mm': 58.0,
        'body_width_mm': 38.0,
        'body_height_mm': 8.0,
        'pocket_length_mm': 58.4,
        'pocket_width_mm': 38.4,
        'nominal_side_clearance_mm': 0.2,
        'bottom_skin_mm': 1.0,
        'channel_height_mm': 7.0,
        'key_chamfer_mm': 4.0,
        'radial_inner_edge_mm': 30.0,
        'radial_outer_edge_mm': 88.4,
    },
    'fasteners': {
        'lid_screw_count': 12,
        'lid_screw_clearance_diameter_mm': 3.4,
        'recommended': '12x M3x18 or M3x20 screws, washers, nuts',
    },
    'microphone_socket': {
        'base_socket_diameter_mm': 20.4,
        'insert_neck_diameter_mm': 20.0,
        'diametral_clearance_mm': 0.4,
        'flange_diameter_mm': 30.0,
        'insert_options_bore_mm': [6.0, 9.5, 12.7, 2.5],
    },
    'port_plug': {
        'insertion_length_mm': 12.0,
        'outer_section_width_mm': 14.2,
        'outer_section_height_mm': 7.4,
        'width_at_10mm_depth_mm': 10.2,
        'tip_width_mm': 9.2,
        'tip_height_mm': 6.8,
        'flange_width_mm': 23.0,
        'flange_height_mm': 14.0,
        'flange_thickness_mm': 2.4,
        'minimum_nominal_side_clearance_mm': 0.3,
        'note': 'Tapered to the P01 outer-port envelope; print flange-down, insert narrow tip first.',
    },
    'turntable': {
        'base_outer_diameter_mm': 180.0,
        'top_outer_diameter_mm': 164.0,
        'index_increment_deg': 45,
        'mount_post_centres_mm': [[24,24],[-24,24],[-24,-24],[24,-24]],
        'mount_post_diameter_mm': 6.0,
        'base_recess_diameter_mm': 6.4,
        'base_recess_depth_mm': 3.0,
    },
    'recommended_analysis_band_hz': [1500, 8000],
    'reference_speed_of_sound_m_s': 343.0,
}

# -----------------------------
# Geometry helpers
# -----------------------------

def clean(g):
    if g.is_empty:
        return g
    g = shapely.set_precision(g, grid_size=0.001)
    if not g.is_valid:
        g = shapely.make_valid(g)
    return g


def circle(x: float, y: float, r: float, resolution: int = 64):
    return Point(x, y).buffer(r, quad_segs=resolution)


def rounded_rect(xmin: float, ymin: float, xmax: float, ymax: float, r: float):
    if r <= 0:
        return box(xmin, ymin, xmax, ymax)
    core = box(xmin + r, ymin + r, xmax - r, ymax - r)
    return core.buffer(r, join_style='round')


def rings_of(g):
    if g.is_empty:
        return
    if isinstance(g, Polygon):
        yield g.exterior
        for ring in g.interiors:
            yield ring
    elif isinstance(g, MultiPolygon):
        for p in g.geoms:
            yield from rings_of(p)
    elif isinstance(g, GeometryCollection):
        for x in g.geoms:
            if isinstance(x, (Polygon, MultiPolygon)):
                yield from rings_of(x)


def polygons_of(g):
    if g.is_empty:
        return
    if isinstance(g, Polygon):
        yield g
    elif isinstance(g, MultiPolygon):
        for p in g.geoms:
            yield p
    elif isinstance(g, GeometryCollection):
        for x in g.geoms:
            if isinstance(x, Polygon):
                yield x
            elif isinstance(x, MultiPolygon):
                for p in x.geoms:
                    yield p


def tri_area2(coords):
    (x0, y0), (x1, y1), (x2, y2) = coords
    return (x1-x0)*(y2-y0) - (y1-y0)*(x2-x0)


def add_horizontal_surface(vertices, faces, geom, z: float, up: bool):
    geom = clean(geom)
    if geom.is_empty:
        return
    tris = shapely.constrained_delaunay_triangles(geom)
    for tri in getattr(tris, 'geoms', [tris]):
        if not isinstance(tri, Polygon) or tri.area < 1e-9:
            continue
        # CDT should respect boundaries, but guard against numerical leftovers.
        rp = tri.representative_point()
        if not geom.covers(rp):
            continue
        coords = list(tri.exterior.coords)[:3]
        if tri_area2(coords) < 0:
            coords = [coords[0], coords[2], coords[1]]
        if not up:
            coords = [coords[0], coords[2], coords[1]]
        idx = []
        for x, y in coords:
            idx.append(len(vertices))
            vertices.append([x, y, z])
        faces.append(idx)


def add_vertical_walls(vertices, faces, geom, z0: float, z1: float):
    """Add side walls for a single atomic cell.

    The diagonal is chosen from lexicographically ordered endpoints so two
    adjacent cells generate identical internal triangles, which can be removed.
    """
    geom = clean(geom)
    for ring in rings_of(geom):
        coords = list(ring.coords)
        for i in range(len(coords)-1):
            a = (float(coords[i][0]), float(coords[i][1]))
            b = (float(coords[i+1][0]), float(coords[i+1][1]))
            if abs(a[0]-b[0])+abs(a[1]-b[1]) < 1e-9:
                continue
            p, q = sorted([a, b])
            base = len(vertices)
            vertices.extend([
                [p[0], p[1], z0],
                [q[0], q[1], z0],
                [q[0], q[1], z1],
                [p[0], p[1], z1],
            ])
            faces.append([base, base+1, base+2])
            faces.append([base, base+2, base+3])


def layered_mesh(layers: Sequence[Tuple[float, float, Any]], name: str = '') -> trimesh.Trimesh:
    """Build a watertight 2.5D union from layer cross sections.

    All profile boundaries are polygonized into atomic planar cells. A prism is
    generated for every occupied cell/layer interval. Exact internal duplicate
    triangles are then removed. This avoids T-junctions when a channel reaches an
    exterior edge or when a raised feature starts on a larger lower profile.
    """
    from shapely.ops import polygonize

    layers = [(float(a), float(b), clean(g)) for a,b,g in layers if b > a and not g.is_empty]
    layers.sort(key=lambda x: x[0])
    if not layers:
        raise ValueError(f'No geometry for {name}')

    linework = unary_union([g.boundary for _,_,g in layers])
    cells = [clean(c) for c in polygonize(linework) if c.area > 1e-8]
    if not cells:
        raise ValueError(f'Polygonization produced no cells for {name}')

    vertices: List[List[float]] = []
    faces: List[List[int]] = []
    for cell in cells:
        rp = cell.representative_point()
        for z0, z1, g in layers:
            if g.covers(rp):
                add_horizontal_surface(vertices, faces, cell, z0, up=False)
                add_horizontal_surface(vertices, faces, cell, z1, up=True)
                add_vertical_walls(vertices, faces, cell, z0, z1)

    mesh = trimesh.Trimesh(vertices=np.asarray(vertices), faces=np.asarray(faces), process=False)
    mesh.merge_vertices(digits_vertex=5)
    mesh.remove_unreferenced_vertices()

    # Remove paired internal faces after the atomic-cell prisms are assembled.
    sorted_faces = np.sort(mesh.faces, axis=1)
    _, inverse, counts = np.unique(sorted_faces, axis=0, return_inverse=True, return_counts=True)
    keep = counts[inverse] == 1
    mesh.update_faces(keep)
    mesh.remove_unreferenced_vertices()
    trimesh.repair.fix_normals(mesh, multibody=True)
    mesh.metadata['name'] = name
    return mesh

def transform_geom(g, angle_deg=0.0, tx=0.0, ty=0.0):
    h = affinity.rotate(g, angle_deg, origin=(0,0), use_radians=False)
    h = affinity.translate(h, xoff=tx, yoff=ty)
    return clean(h)


def polyline_channel(points, width, cap='flat'):
    cap_style = 'flat' if cap == 'flat' else 'round'
    return clean(LineString(points).buffer(width/2, cap_style=cap_style, join_style='round'))


def module_outline(length=58.0, width=38.0, chamfer=4.0):
    L, W, c = length/2, width/2, chamfer
    pts = [(-L,-W),(L,-W),(L,W-c),(L-c,W),(-L,W)]
    return clean(Polygon(pts))


def module_pocket_outline(clear=0.2):
    # clearance is per side; preserve key chamfer and add clearance conservatively.
    L = P['module']['body_length_mm']/2 + clear
    W = P['module']['body_width_mm']/2 + clear
    c = P['module']['key_chamfer_mm'] + 0.15
    pts = [(-L,-W),(L,-W),(L,W-c),(L-c,W),(-L,W)]
    return clean(Polygon(pts))


def rotate_translate_module(g, direction: str):
    centers = {'E': (59.2,0,0), 'N': (0,59.2,90), 'W': (-59.2,0,180), 'S': (0,-59.2,-90)}
    tx,ty,a = centers[direction]
    return transform_geom(g,a,tx,ty)


def mesh_export(mesh: trimesh.Trimesh, path: Path):
    path.parent.mkdir(parents=True, exist_ok=True)
    mesh.export(path, file_type='stl')


def combine_meshes(meshes: Sequence[trimesh.Trimesh], translations: Sequence[Tuple[float,float,float]] | None = None):
    out=[]
    if translations is None:
        translations=[(0,0,0)]*len(meshes)
    for m,t in zip(meshes, translations):
        c=m.copy(); c.apply_translation(t); out.append(c)
    return trimesh.util.concatenate(out)

# -----------------------------
# Head base geometry
# -----------------------------

def head_outer_profile():
    horiz = rounded_rect(-105,-27,105,27,4)
    vert = rounded_rect(-27,-105,27,105,4)
    cen = circle(0,0,50,64)
    return clean(unary_union([horiz,vert,cen]))

OUTER = head_outer_profile()
SCREW_POS = [(32,32),(-32,32),(-32,-32),(32,-32),
             (82,23),(82,-23),(-82,23),(-82,-23),
             (23,82),(-23,82),(23,-82),(-23,-82)]
SCREW_HOLES = unary_union([circle(x,y,1.7,24) for x,y in SCREW_POS])
MOUNT_POS = [(24,24),(-24,24),(-24,-24),(24,-24)]
MOUNT_RECESSES = unary_union([circle(x,y,3.2,24) for x,y in MOUNT_POS])
MIC_SOCKET = circle(0,0,10.2,48)
CENTER_CHAMBER = circle(0,0,18,64)

# Local East arm air geometry.
INNER_CH = box(16.5,-4.5,30.8,4.5)
POCKET_LOCAL = affinity.translate(module_pocket_outline(0.2), xoff=59.2)
OUTER_CH = Polygon([(87.6,-4.5),(95,-5.4),(106,-7.6),(111,-7.6),
                    (111,7.6),(106,7.6),(95,5.4),(87.6,4.5)])
ARM_AIR_LOCAL = clean(unary_union([INNER_CH,POCKET_LOCAL,OUTER_CH]))
ARM_AIRS=[]
for d,a in [('E',0),('N',90),('W',180),('S',-90)]:
    ARM_AIRS.append(transform_geom(ARM_AIR_LOCAL,a,0,0))
AIRSPACE = clean(unary_union([CENTER_CHAMBER]+ARM_AIRS))

BASE_P0 = clean(OUTER.difference(unary_union([SCREW_HOLES,MIC_SOCKET,MOUNT_RECESSES])))
BASE_P1 = clean(OUTER.difference(unary_union([SCREW_HOLES,AIRSPACE,MOUNT_RECESSES])))
BASE_P2 = clean(OUTER.difference(unary_union([SCREW_HOLES,AIRSPACE])))
base_mesh = layered_mesh([(0,2.4,BASE_P0),(2.4,3.0,BASE_P1),(3.0,10.4,BASE_P2)], 'P01_acoustic_base_tray')
mesh_export(base_mesh, STL/'P01_acoustic_base_tray.stl')

# Lid and orientation arrow.
LID_MAIN = clean(OUTER.difference(SCREW_HOLES))
arrow = Polygon([(-6,89),(0,101),(6,89),(2.5,89),(2.5,82),(-2.5,82),(-2.5,89)])
lid_mesh = layered_mesh([(0,3.0,LID_MAIN),(3.0,3.8,arrow)], 'P02_sealing_lid')
mesh_export(lid_mesh, STL/'P02_sealing_lid.stl')

# -----------------------------
# Module geometries
# -----------------------------
MOD_OUT = module_outline()
EXTRACT_HOLE = circle(21.5,-12.0,1.6,20)

# Module channel definitions in local coordinates.
channel_A = clean(unary_union([
    polyline_channel([(-29,0),(29,0)],10.0),
]))
points_B=[(-29,0),(-24,0),(-18,12),(-8,12),(-2,-12),(8,-12),(14,12),(24,12),(29,0)]
channel_B = polyline_channel(points_B,9.0)
# Add short straight interface pads to assure full opening at ends.
channel_B = clean(unary_union([channel_B, box(-29.5,-4.5,-23,4.5), box(23,-4.5,29.5,4.5)]))
channel_C_main = polyline_channel([(-29,0),(29,0)],10.0)
stub_C = polyline_channel([(0,0),(0,11.5),(14,11.5)],6.0)
channel_C = clean(unary_union([channel_C_main,stub_C]))
points_D=[(-29,0),(-20,-10),(20,-10),(29,0)]
channel_D_main=polyline_channel(points_D,9.0)
stub_D=polyline_channel([(0,-10),(0,13.5),(-10,13.5)],6.0)
channel_D=clean(unary_union([channel_D_main,stub_D]))

MODULE_CHANNELS={'A_short_straight':channel_A,'B_long_serpentine':channel_B,
                 'C_straight_short_stub':channel_C,'D_dogleg_long_stub':channel_D}
module_meshes={}
for nm,ch in MODULE_CHANNELS.items():
    p0=clean(MOD_OUT.difference(EXTRACT_HOLE))
    p1=clean(MOD_OUT.difference(unary_union([EXTRACT_HOLE,ch])))
    m=layered_mesh([(0,1.0,p0),(1.0,8.0,p1)], f'P06_module_{nm}')
    module_meshes[nm]=m
    mesh_export(m,STL/f'P06_module_{nm}.stl')

# Baseline straight module is same geometry, separate file/name for clarity.
mesh_export(module_meshes['A_short_straight'].copy(), STL/'P05_module_straight_baseline_PRINT_4.stl')

# Blocking module.
block_p=clean(MOD_OUT.difference(EXTRACT_HOLE))
block_mesh=layered_mesh([(0,8.0,block_p)],'P07_module_blocking_blank')
mesh_export(block_mesh,STL/'P07_module_blocking_blank.stl')

# -----------------------------
# Microphone inserts
# -----------------------------

def mic_insert_mesh(bore_d: float, name: str):
    bore=circle(0,0,bore_d/2,48)
    flange=clean(circle(0,0,15,64).difference(bore))
    neck=clean(circle(0,0,10.0,64).difference(bore))
    ridge=clean(circle(0,0,10.12,64).difference(bore))
    return layered_mesh([(0,2.4,flange),(2.4,4.4,neck),(4.4,4.9,ridge),(4.9,6.0,neck)],name)

for bore,label in [(6.0,'ID6_0'),(9.5,'ID9_5'),(12.7,'ID12_7'),(2.5,'blank_with_2_5_pilot')]:
    m=mic_insert_mesh(bore,f'P03_mic_insert_{label}')
    mesh_export(m,STL/f'P03_mic_insert_{label}.stl')

# -----------------------------
# Port plug
# -----------------------------
# P01's outer passage is a tapered plan-view diffuser: at the physical side
# plane x=105 mm its opening is ~14.8 mm wide, narrowing to 10.8 mm at
# 10 mm insertion depth and ~10.31 mm at 12 mm.  V1.0.0 incorrectly used a
# constant-width rectangular shaft and checked only the face width.  V1.0.1
# uses a true tapered shaft and validates the complete insertion envelope.

def chamfered_rect_coords(width: float, height: float, chamfer: float):
    w, h, c = width/2.0, height/2.0, min(chamfer, width/4.0, height/4.0)
    return [(-w+c,-h),(w-c,-h),(w,-h+c),(w,h-c),
            (w-c,h),(-w+c,h),(-w,h-c),(-w,-h+c)]


def tapered_port_plug_mesh() -> trimesh.Trimesh:
    flange_z = P['port_plug']['flange_thickness_mm']
    # The pull tab is coplanar with the flange so the part prints flange-down
    # without support; the tapered shaft then grows vertically from the bed.
    flange_main = rounded_rect(-11.5,-7.0,11.5,7.0,1.5)
    pull_tab = rounded_rect(-4.5,6.0,4.5,14.0,1.2)
    flange_prof = clean(unary_union([flange_main, pull_tab]))

    # (model z, width, height, corner chamfer).  In use the model z-axis is the
    # insertion axis.  z=flange_z is the port face; the highest/narrowest
    # section is inserted deepest.  Profiles follow the two linear tapers in
    # OUTER_CH with >=0.3 mm nominal clearance per side.
    prof_data = [
        (flange_z,       14.2, 7.4, 0.55),   # depth 0 mm
        (flange_z+10.0, 10.2, 7.3, 0.50),   # depth 10 mm
        (flange_z+11.4,  9.85,7.2, 0.45),   # depth 11.4 mm
        (flange_z+12.0,  9.2, 6.8, 0.40),   # lead-in tip at depth 12 mm
    ]
    profiles=[]
    for z,w,h,c in prof_data:
        coords=chamfered_rect_coords(w,h,c)
        profiles.append((z,coords,clean(Polygon(coords))))

    vertices: List[List[float]]=[]
    faces: List[List[int]]=[]

    # Flange bottom and outer walls.
    add_horizontal_surface(vertices,faces,flange_prof,0.0,up=False)
    add_vertical_walls(vertices,faces,flange_prof,0.0,flange_z)
    # Flange top, excluding the shaft footprint so the union has no internal cap.
    shaft_bottom=profiles[0][2]
    add_horizontal_surface(vertices,faces,clean(flange_prof.difference(shaft_bottom)),flange_z,up=True)

    # Loft the tapered shaft between equal-vertex-count chamfered rectangles.
    for (z0,c0,_),(z1,c1,_) in zip(profiles[:-1],profiles[1:]):
        n=len(c0)
        for i in range(n):
            j=(i+1)%n
            base=len(vertices)
            vertices.extend([[c0[i][0],c0[i][1],z0],
                             [c0[j][0],c0[j][1],z0],
                             [c1[j][0],c1[j][1],z1],
                             [c1[i][0],c1[i][1],z1]])
            faces.append([base,base+1,base+2])
            faces.append([base,base+2,base+3])
    add_horizontal_surface(vertices,faces,profiles[-1][2],profiles[-1][0],up=True)

    mesh=trimesh.Trimesh(vertices=np.asarray(vertices),faces=np.asarray(faces),process=False)
    mesh.merge_vertices(digits_vertex=5)
    mesh.remove_unreferenced_vertices()
    trimesh.repair.fix_normals(mesh,multibody=True)
    mesh.metadata['name']='P04_port_plug_tapered_v1_0_1'
    return mesh

port_plug=tapered_port_plug_mesh()
mesh_export(port_plug,STL/'P04_port_plug_PRINT_4.stl')

# -----------------------------
# Fit and sealing coupons
# -----------------------------
# Module fit coupon with three slots; key is miniature module section.
coupon_outer=rounded_rect(-58,-23,58,23,3)
slot_centers=[-38,0,38]
slot_dims=[(20.2,38.2),(20.5,38.5),(20.8,38.8)]
slots=[]
for cx,(L,W) in zip(slot_centers,slot_dims):
    slots.append(box(cx-L/2,-W/2,cx+L/2,W/2))
fit_p0=coupon_outer
fit_p1=clean(coupon_outer.difference(unary_union(slots)))
fit_coupon=layered_mesh([(0,2.0,fit_p0),(2.0,10.0,fit_p1)],'P08_module_fit_coupon')
mesh_export(fit_coupon,STL/'P08_module_fit_coupon.stl')
fit_key_outline=Polygon([(-10,-19),(10,-19),(10,15),(6,19),(-10,19)])
fit_key=layered_mesh([(0,8.0,fit_key_outline)],'P09_module_fit_key')
mesh_export(fit_key,STL/'P09_module_fit_key.stl')

# Mic gauge: holes 19.8, 20.0, 20.2, 20.4 mm from left to right.
gauge_outer=rounded_rect(-60,-18,60,18,3)
gauge_holes=unary_union([circle(x,0,d/2,48) for x,d in zip([-45,-15,15,45],[19.8,20.0,20.2,20.4])])
mic_gauge=layered_mesh([(0,4.0,clean(gauge_outer.difference(gauge_holes)))],'P10_mic_fit_gauge')
mesh_export(mic_gauge,STL/'P10_mic_fit_gauge.stl')

# Seal/screw coupon.
seal_outer=rounded_rect(-32,-18,32,18,3)
seal_screws=unary_union([circle(-21,12,1.7,24),circle(21,12,1.7,24),circle(-21,-12,1.7,24),circle(21,-12,1.7,24)])
seal_channel=box(-34,-5,34,5)
seal_base0=clean(seal_outer.difference(seal_screws))
seal_base1=clean(seal_outer.difference(unary_union([seal_screws,seal_channel])))
seal_coupon_base=layered_mesh([(0,2.4,seal_base0),(2.4,10.4,seal_base1)],'P11_seal_coupon_base')
seal_coupon_lid=layered_mesh([(0,3.0,clean(seal_outer.difference(seal_screws)))],'P12_seal_coupon_lid')
mesh_export(seal_coupon_base,STL/'P11_seal_coupon_base.stl')
mesh_export(seal_coupon_lid,STL/'P12_seal_coupon_lid.stl')
seal_gasket_profile=clean(seal_outer.difference(unary_union([seal_screws,seal_channel])))
seal_gasket=layered_mesh([(0,0.8,seal_gasket_profile)],'P12b_seal_coupon_gasket_2piece_TPU')
mesh_export(seal_gasket,STL/'P12b_seal_coupon_gasket_2piece_TPU.stl')
for i,c in enumerate(sorted(seal_gasket.split(only_watertight=False), key=lambda m: m.centroid[1], reverse=True), start=1):
    mesh_export(c,STL/f'P12b_seal_coupon_gasket_piece_{i}.stl')

# -----------------------------
# Gaskets for B1 and B2
# -----------------------------
# Top air not including empty module pockets; instead include installed module grooves.
FIXED_AIR=clean(unary_union([CENTER_CHAMBER]+[
    transform_geom(clean(unary_union([INNER_CH,OUTER_CH])),a,0,0) for a in [0,90,180,-90]
]))

def global_module_channel(ch,direction):
    return rotate_translate_module(ch,direction)

channels_B1=[global_module_channel(channel_A,d) for d in ['N','E','S','W']]
channels_B2=[global_module_channel(channel_A,'N'),global_module_channel(channel_B,'E'),
             global_module_channel(channel_C,'S'),global_module_channel(channel_D,'W')]

def gasket_for(channels,name):
    air=clean(unary_union([FIXED_AIR]+channels))
    prof=clean(OUTER.difference(unary_union([SCREW_HOLES,air])))
    return layered_mesh([(0,0.8,prof)],name),prof

gasket_B1,gasket_B1_prof=gasket_for(channels_B1,'P13_gasket_B1_symmetric_TPU_or_cut_template')
gasket_B2,gasket_B2_prof=gasket_for(channels_B2,'P14_gasket_B2_encoded_TPU_or_cut_template')
mesh_export(gasket_B1,STL/'P13_gasket_B1_symmetric_4piece_TPU.stl')
mesh_export(gasket_B2,STL/'P14_gasket_B2_encoded_4piece_TPU.stl')

# Also export the four quadrant pieces individually for easier placement.
def export_quadrants(mesh, prefix):
    comps=list(mesh.split(only_watertight=False))
    labels=[]
    for c in comps:
        x,y,_=c.centroid
        label=('N' if y>=0 else 'S')+('E' if x>=0 else 'W')
        labels.append((label,c))
    for label,c in sorted(labels):
        mesh_export(c,STL/f'{prefix}_{label}.stl')
export_quadrants(gasket_B1,'P13_gasket_B1_piece')
export_quadrants(gasket_B2,'P14_gasket_B2_piece')

# -----------------------------
# Turntable
# -----------------------------
def spoke_rect(angle_deg, r0, r1, width):
    g=box(r0,-width/2,r1,width/2)
    return transform_geom(g,angle_deg)

lower_ring=clean(circle(0,0,90,96).difference(circle(0,0,68,96)))
lower_hub=circle(0,0,18,48)
lower_spokes=[spoke_rect(a,14,70,12) for a in range(0,360,45)]
lower_profile=clean(unary_union([lower_ring,lower_hub]+lower_spokes))
lower_center_hole=circle(0,0,5.10,32)
detent_holes=unary_union([circle(76*math.cos(math.radians(a)),76*math.sin(math.radians(a)),2.15,20) for a in range(0,360,45)])
lower_profile=clean(lower_profile.difference(unary_union([lower_center_hole,detent_holes])))
turn_base=layered_mesh([(0,6.0,lower_profile)],'P15_turntable_base_45deg_index')
mesh_export(turn_base,STL/'P15_turntable_base_45deg_index.stl')

upper_ring=clean(circle(0,0,82,96).difference(circle(0,0,60,96)))
upper_hub=circle(0,0,24,48)
upper_spokes=[spoke_rect(a,20,63,14) for a in range(0,360,45)]
upper_main=clean(unary_union([upper_ring,upper_hub]+upper_spokes))
upper_center_hole=circle(0,0,5.30,32)
upper_detent=circle(76,0,2.2,20)
upper_main=clean(upper_main.difference(unary_union([upper_center_hole,upper_detent])))
pads=unary_union([circle(x,y,7,32) for x,y in MOUNT_POS])
posts=unary_union([circle(x,y,3.0,24) for x,y in MOUNT_POS])
turn_top=layered_mesh([(0,5.0,upper_main),(5.0,9.0,pads),(9.0,12.0,posts)],'P16_turntable_top_with_head_mounts')
mesh_export(turn_top,STL/'P16_turntable_top_with_head_mounts.stl')

pin_flange=circle(0,0,8,40)
pin_shaft=circle(0,0,4.9,32)
center_pin=layered_mesh([(0,2.0,pin_flange),(2.0,15.0,pin_shaft)],'P17_turntable_center_pin')
mesh_export(center_pin,STL/'P17_turntable_center_pin.stl')

det_shaft=circle(0,0,1.9,24)
det_head=circle(0,0,5.0,32)
det_pin=layered_mesh([(0,11.0,det_shaft),(11.0,14.0,det_head)],'P18_turntable_detent_pin')
mesh_export(det_pin,STL/'P18_turntable_detent_pin.stl')

# -----------------------------
# Combined print plates
# -----------------------------
plate_modules=[]; trans=[]
mods_for_plate=[module_meshes['A_short_straight']]*4 + [module_meshes['A_short_straight'],module_meshes['B_long_serpentine'],module_meshes['C_straight_short_stub'],module_meshes['D_dogleg_long_stub'],block_mesh]
positions=[(-70,-30,0),(-25,-30,0),(20,-30,0),(65,-30,0),(-70,25,0),(-25,25,0),(20,25,0),(65,25,0),(0,75,0)]
# Rotate modules so long axis along y for tighter packing if needed; leave as is and spread.
plate=combine_meshes(mods_for_plate,positions)
mesh_export(plate,STL/'PLATE_modules_baseline4_encoded4_blank1.stl')

# Small parts plate: four plugs + mic inserts + pins.
small=[]; pos=[]
for i in range(4):
    small.append(port_plug); pos.append((-55+i*35,-25,0))
for i,(bore,label) in enumerate([(6.0,'6'),(9.5,'9.5'),(12.7,'12.7'),(2.5,'blank')]):
    small.append(mic_insert_mesh(bore,'tmp')); pos.append((-52.5+i*35,20,0))
small.extend([center_pin,det_pin]); pos.extend([(-18,55,0),(18,55,0)])
small_plate=combine_meshes(small,pos)
mesh_export(small_plate,STL/'PLATE_small_parts.stl')

# -----------------------------
# SVG templates
# -----------------------------
def svg_path_for_geom(g, flip_y=True):
    parts=[]
    for poly in polygons_of(g):
        rings=[poly.exterior]+list(poly.interiors)
        for ring in rings:
            coords=list(ring.coords)
            if not coords: continue
            x0,y0=coords[0]; y0=-y0 if flip_y else y0
            seg=[f'M {x0:.3f},{y0:.3f}']
            for x,y in coords[1:]:
                y=-y if flip_y else y
                seg.append(f'L {x:.3f},{y:.3f}')
            seg.append('Z')
            parts.append(' '.join(seg))
    return ' '.join(parts)

def write_svg(g,path:Path,margin=5):
    minx,miny,maxx,maxy=g.bounds
    w=maxx-minx+2*margin; h=maxy-miny+2*margin
    # y flipped, viewbox starts at -maxy
    vb_x=minx-margin; vb_y=-maxy-margin
    p=svg_path_for_geom(g,True)
    txt=f'''<svg xmlns="http://www.w3.org/2000/svg" width="{w:.3f}mm" height="{h:.3f}mm" viewBox="{vb_x:.3f} {vb_y:.3f} {w:.3f} {h:.3f}">
  <path d="{p}" fill="none" stroke="black" stroke-width="0.2" fill-rule="evenodd"/>
</svg>\n'''
    path.write_text(txt,encoding='utf-8')

write_svg(gasket_B1_prof,SVG/'gasket_B1_symmetric_1to1.svg')
write_svg(gasket_B2_prof,SVG/'gasket_B2_encoded_1to1.svg')
write_svg(seal_gasket_profile,SVG/'seal_coupon_gasket_1to1.svg')
write_svg(OUTER,SVG/'head_outer_outline_1to1.svg')

# -----------------------------
# Geometry/Acoustics data
# -----------------------------
def path_length(points):
    return sum(math.dist(a,b) for a,b in zip(points[:-1],points[1:]))

module_metrics={
    'N_A_short_straight': {'main_centerline_mm':58.0,'main_channel_width_mm':10.0,'stub_centerline_mm':0.0},
    'E_B_long_serpentine': {'main_centerline_mm':path_length(points_B),'main_channel_width_mm':9.0,'stub_centerline_mm':0.0},
    'S_C_straight_short_stub': {'main_centerline_mm':58.0,'main_channel_width_mm':10.0,'stub_centerline_mm':11.5+14.0},
    'W_D_dogleg_long_stub': {'main_centerline_mm':path_length(points_D),'main_channel_width_mm':9.0,'stub_centerline_mm':23.5+10.0},
}
for k,v in module_metrics.items():
    v['estimated_total_centerline_to_chamber_mm']=round(12.0+17.0+v['main_centerline_mm'],2)
    if v['stub_centerline_mm']>0:
        L=v['stub_centerline_mm']/1000
        v['quarter_wave_estimate_hz']=round(P['reference_speed_of_sound_m_s']/(4*L),1)
    w=v['main_channel_width_mm']; h=7.0
    v['main_area_mm2']=round(w*h,2)
    v['main_hydraulic_diameter_mm']=round(2*w*h/(w+h),3)
P['module_metrics']=module_metrics
P['fixed_channel_metrics']={'area_mm2':72.0,'hydraulic_diameter_mm':round(2*9*8/(9+8),3)}
(SRC/'design_parameters_v1.json').write_text(json.dumps(P,indent=2,ensure_ascii=False),encoding='utf-8')

# -----------------------------
# Validation report
# -----------------------------
all_stls=sorted(STL.glob('*.stl'))
validation=[]
for f in all_stls:
    mesh=trimesh.load_mesh(f,force='mesh',process=True)
    b=mesh.bounds
    ext=b[1]-b[0]
    validation.append({
        'file':f.name,
        'watertight':bool(mesh.is_watertight),
        'winding_consistent':bool(mesh.is_winding_consistent),
        'components':int(len(mesh.split(only_watertight=False))),
        'faces':int(len(mesh.faces)),
        'vertices':int(len(mesh.vertices)),
        'bounds_min_mm':[round(float(x),3) for x in b[0]],
        'bounds_max_mm':[round(float(x),3) for x in b[1]],
        'size_mm':[round(float(x),3) for x in ext],
        'volume_cm3':round(abs(float(mesh.volume))/1000,3),
        'solid_mass_PLA_g':round(abs(float(mesh.volume))/1000*1.24,1),
    })

# Assembly dimensional checks.
checks=[]
def check(name,actual,criterion,passed,notes=''):
    checks.append({'check':name,'actual':actual,'criterion':criterion,'pass':bool(passed),'notes':notes})
check('module length fit',58.0,'pocket 58.4; 0.2 mm/side',58.0<58.4)
check('module width fit',38.0,'pocket 38.4; 0.2 mm/side',38.0<38.4)
check('module height flush',8.0,'base pocket depth=10.4-2.4=8.0',abs(8.0-(10.4-2.4))<1e-9)
check('mic insert fit',20.0,'socket 20.4; 0.4 mm diametral clearance',20.0<20.4)
check('turntable post fit',6.0,'head recess 6.4; 0.4 mm diametral clearance',6.0<6.4)
check('turntable post depth',3.0,'head recess depth 3.0',True,'Nominal flush axial location; support pads provide 4 mm underside clearance.')
check('lid screw alignment',len(SCREW_POS),'same coordinate list used for base and lid',len(SCREW_POS)==12)
check('printer bed X/Y',max(base_mesh.extents[:2]),'<= 220 mm',max(base_mesh.extents[:2])<=220)
check('fixed vs module area A/C',70.0,'fixed area 72 mm²; difference <5%',abs(70-72)/72<0.05)

# Exact 2D interface/collision checks.
for d in ['N','E','S','W']:
    pocket=rotate_translate_module(module_pocket_outline(0.2),d)
    mod=rotate_translate_module(MOD_OUT,d)
    check(f'module contained in pocket {d}', round(pocket.difference(mod).area,3), 'pocket fully contains module', pocket.covers(mod))
check('screw holes avoid acoustic airspace', round(SCREW_HOLES.intersection(AIRSPACE).area,6), 'intersection area = 0', SCREW_HOLES.intersection(AIRSPACE).area < 1e-6)
check('turntable recesses avoid acoustic airspace', round(MOUNT_RECESSES.intersection(AIRSPACE).area,6), 'intersection area = 0', MOUNT_RECESSES.intersection(AIRSPACE).area < 1e-6)
for d,ch in [('N',channel_A),('E',channel_B),('S',channel_C),('W',channel_D)]:
    cg=global_module_channel(ch,d)
    overlap=cg.intersection(FIXED_AIR).area
    check(f'module channel overlaps fixed passages {d}', round(overlap,3), 'positive overlap at both interfaces; total overlap > 5 mm²', overlap>5.0)
check('B1 gasket does not obstruct B1 air', round(gasket_B1_prof.intersection(clean(unary_union([FIXED_AIR]+channels_B1))).area,6), 'intersection area = 0', gasket_B1_prof.intersection(clean(unary_union([FIXED_AIR]+channels_B1))).area<1e-6)
check('B2 gasket does not obstruct B2 air', round(gasket_B2_prof.intersection(clean(unary_union([FIXED_AIR]+channels_B2))).area,6), 'intersection area = 0', gasket_B2_prof.intersection(clean(unary_union([FIXED_AIR]+channels_B2))).area<1e-6)
# Validate the complete tapered P04 insertion envelope, not only the mouth.
def port_width_at_depth(depth_mm: float) -> float:
    x=105.0-depth_mm
    cut=OUTER_CH.intersection(LineString([(x,-100.0),(x,100.0)]))
    if cut.is_empty:
        return 0.0
    ys=[]
    geoms=[cut] if cut.geom_type=='LineString' else list(cut.geoms)
    for g in geoms:
        ys.extend([float(v[1]) for v in g.coords])
    return max(ys)-min(ys)

plug_depths=np.asarray([0.0,10.0,11.4,12.0])
plug_widths=np.asarray([14.2,10.2,9.85,9.2])
def plug_width_at_depth(depth_mm: float) -> float:
    return float(np.interp(depth_mm,plug_depths,plug_widths))

samples=np.linspace(0.0,12.0,121)
clearances=np.asarray([port_width_at_depth(d)-plug_width_at_depth(d) for d in samples])
check('port plug full tapered insertion',round(float(clearances.min()),3),'>= 0.55 mm total lateral clearance over 0–12 mm depth',float(clearances.min())>=0.55,
      'V1.0.0 checked only the outer face; V1.0.1 checks the complete taper.')
check('port plug vertical fit',7.4,'port height 8.0 mm; 0.3 mm clearance top and bottom',7.4<=8.0)
check('port plug flange coverage','23.0 x 14.0','larger than 14.8 x 8.0 mouth',23.0>14.8 and 14.0>8.0)

report={'generated_files':validation,'assembly_checks':checks,'all_individual_parts_watertight':all(x['watertight'] for x in validation if not x['file'].startswith('PLATE_')),
        'note':'PLATE files intentionally contain multiple disconnected watertight bodies; individual part STLs are the authoritative geometry.'}
(SRC/'validation_report.json').write_text(json.dumps(report,indent=2,ensure_ascii=False),encoding='utf-8')

# Markdown validation report.
lines=['# 几何与装配验证报告','',f"生成版本：{P['version']}",'',
       f"独立零件 STL 全部水密：**{report['all_individual_parts_watertight']}**",'',
       '## 装配尺寸检查','', '| 检查 | 实际值 | 判据 | 结果 | 备注 |','|---|---:|---|:---:|---|']
for c in checks:
    lines.append(f"| {c['check']} | {c['actual']} | {c['criterion']} | {'通过' if c['pass'] else '失败'} | {c['notes']} |")
lines += ['', '## STL 网格检查','', '| 文件 | 水密 | 一致绕向 | 组件数 | 尺寸 mm | 实体体积 cm³ |','|---|:---:|:---:|---:|---|---:|']
for v in validation:
    lines.append(f"| {v['file']} | {v['watertight']} | {v['winding_consistent']} | {v['components']} | {v['size_mm']} | {v['volume_cm3']} |")
lines += ['', '说明：组合打印板 `PLATE_*` 包含多个彼此分离的水密实体，所以组件数大于 1 是预期行为。独立零件 STL 是尺寸与装配验证的权威版本。']
(DOC/'VALIDATION_REPORT.md').write_text('\n'.join(lines),encoding='utf-8')

# -----------------------------
# Preview graphics and assembly GLB
# -----------------------------
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
from matplotlib.patches import Polygon as MplPolygon

fig,ax=plt.subplots(figsize=(9,9))
# outer profile
for poly in polygons_of(OUTER):
    x,y=poly.exterior.xy; ax.fill(x,y,alpha=0.15,edgecolor='black')
# fixed air
for poly in polygons_of(FIXED_AIR):
    x,y=poly.exterior.xy; ax.fill(x,y,alpha=0.45)
# pockets and module channels encoded
for d,ch in [('N',channel_A),('E',channel_B),('S',channel_C),('W',channel_D)]:
    g=global_module_channel(ch,d)
    for poly in polygons_of(g):
        x,y=poly.exterior.xy; ax.fill(x,y,alpha=0.75)
for x,y in SCREW_POS:
    ax.add_patch(plt.Circle((x,y),1.7,fill=False,linewidth=0.7))
ax.text(0,106,'N',ha='center',va='bottom',fontsize=14)
ax.text(106,0,'E',ha='left',va='center',fontsize=14)
ax.text(0,-106,'S',ha='center',va='top',fontsize=14)
ax.text(-106,0,'W',ha='right',va='center',fontsize=14)
ax.set_aspect('equal'); ax.set_xlim(-115,115); ax.set_ylim(-115,115); ax.set_xlabel('mm'); ax.set_ylabel('mm'); ax.set_title('V1 encoded configuration: fixed passages + interchangeable module channels')
fig.tight_layout(); fig.savefig(PREV/'design_top_view.png',dpi=180); plt.close(fig)

# Exploded schematic using simple rectangles/text.
fig,ax=plt.subplots(figsize=(10,7))
ax.axis('off')
items=[('Lid',5.4),('B1/B2 gasket',4.5),('4 keyed channel modules',3.6),('Acoustic base tray',2.7),('Mic insert from underside',1.8),('Indexed turntable top/base',0.7)]
for label,y in items:
    ax.add_patch(plt.Rectangle((1.4,y),7.2,0.55,fill=False,linewidth=1.5))
    ax.text(5,y+0.275,label,ha='center',va='center',fontsize=12)
    if y>0.8: ax.annotate('',xy=(5,y-0.12),xytext=(5,y-0.45),arrowprops=dict(arrowstyle='->'))
ax.text(5,6.35,'Exploded assembly order',ha='center',fontsize=16)
ax.set_xlim(0,10); ax.set_ylim(0,6.8)
fig.tight_layout(); fig.savefig(PREV/'exploded_assembly.png',dpi=180); plt.close(fig)

# GLB scenes B1/B2. Use colors and lifted lid.
def scene_for(encoded=True):
    sc=trimesh.Scene()
    base=base_mesh.copy(); base.visual.face_colors=[170,170,180,255]; sc.add_geometry(base,node_name='base')
    mapping=[('N',module_meshes['A_short_straight']),('E',module_meshes['B_long_serpentine'] if encoded else module_meshes['A_short_straight']),
             ('S',module_meshes['C_straight_short_stub'] if encoded else module_meshes['A_short_straight']),('W',module_meshes['D_dogleg_long_stub'] if encoded else module_meshes['A_short_straight'])]
    dirs={'E':(0,59.2,0),'N':(90,0,59.2),'W':(180,-59.2,0),'S':(-90,0,-59.2)}
    colors={'N':[220,80,80,255],'E':[80,150,230,255],'S':[90,190,110,255],'W':[220,170,70,255]}
    for d,m in mapping:
        c=m.copy(); a,tx,ty=dirs[d]
        c.apply_transform(trimesh.transformations.rotation_matrix(math.radians(a),[0,0,1]))
        c.apply_translation([tx,ty,2.4])
        c.visual.face_colors=colors[d]; sc.add_geometry(c,node_name=f'module_{d}')
    lid=lid_mesh.copy(); lid.apply_translation([0,0,24]); lid.visual.face_colors=[210,210,220,180]; sc.add_geometry(lid,node_name='lid_exploded')
    return sc

scene_for(False).export(PREV/'assembly_B1_symmetric.glb')
scene_for(True).export(PREV/'assembly_B2_encoded.glb')

# -----------------------------
# Documentation
# -----------------------------
readme=f'''# 四方向模块化内部声学形态编码器 V1.0.1

## 1. 这是什么

本压缩包提供一套可以直接 FDM 3D 打印的、四方向、中心单麦克风声学编码实验平台。它不是对 Sun 等人的三层随机半球超材料外壳的复制，而是将其“不同方向经过不同 acoustic channel module 后形成方向相关频率响应”的思想，缩减为四个确定性的、可更换内部滤波通道。

参考文献：X. Sun et al., *Sound Localization and Separation in 3D Space Using a Single Microphone with a Metamaterial Enclosure*, Advanced Science 7, 1902271, DOI: 10.1002/advs.201902271。原论文把外壳看成多个方向相关 acoustic channel modules，并将单个模块近似为由穿孔层与腔体构成的二阶声学滤波器。V1 采用更容易打印和解释的管道、折线路径及闭端侧支。

设计目标是快速检验：在固定扬声器、固定中心麦克风、已知 chirp 条件下，内部非对称通道是否能使 0°/90°/180°/270° 四个方向形成稳定且能量归一化后仍可区分的传递函数。

## 2. 重要边界

- 这是 proof-of-concept 平台，不是经过 FEM 优化的成品定位器。
- 预计有效信息主要在约 {P['recommended_analysis_band_hz'][0]}–{P['recommended_analysis_band_hz'][1]} Hz；低频方向差异可能较弱。
- 第一轮使用已知 log sweep 或白噪声，单声源、四个离散方向。
- 固定扬声器和麦克风中心位置，只旋转结构，避免搬动扬声器造成混杂。
- 结构同时包含普通声学滤波和形态辅助预处理；不应声称它已经等同于完整物理储备计算。

## 3. 核心尺寸

- 最大 X/Y 跨度：210 mm，适配常见 220×220 mm 打印平台。
- 主体底板：2.4 mm；内部固定通道高度：8.0 mm；主体总高：10.4 mm。
- 上盖厚度：3.0 mm。
- 中心腔半径：18 mm。
- 固定通道：9×8 mm，截面积 72 mm²，水力直径约 {P['fixed_channel_metrics']['hydraulic_diameter_mm']} mm。
- 模块外形：58×38×8 mm；槽位：58.4×38.4×8 mm；每侧名义间隙 0.2 mm。
- 麦克风插芯接口：底座孔 Ø20.4 mm，插芯颈 Ø20.0 mm。
- 12 个上盖 M3 通孔在底座和上盖中由同一坐标表生成。

## 4. 文件夹

- `STL/`：可打印零件与组合打印板。
- `SOURCE/`：参数 JSON、完整 Python 生成脚本、自动验证数据。
- `DOCS/`：装配、打印、实验、AI 交接说明。
- `TEMPLATES/`：1:1 密封垫切割 SVG。
- `PREVIEWS/`：顶视图、爆炸图和 GLB 装配预览。

先阅读：

1. `DOCS/PRINT_AND_BOM.md`
2. `DOCS/ASSEMBLY.md`
3. `DOCS/EXPERIMENT_PLAN.md`
4. `DOCS/AI_HANDOFF.md`
5. `DOCS/VALIDATION_REPORT.md`

## 5. 最小打印方案

必须打印：

- P01 底座 ×1
- P02 上盖 ×1
- P03 与你的麦克风匹配的插芯 ×1
- P05 对称直通模块 ×4
- P06 A/B/C/D 编码模块各 ×1
- P04 入口堵头 ×4
- P13 和 P14 四片式密封垫，或按照 SVG 从 0.8–1.0 mm 硅胶/EVA 切割

推荐打印：P08/P09 配合测试件、P10 麦克风孔规、P11/P12 密封测试件、P15–P18 旋转底座。

## 6. 两个关键实验状态

- **B1 对称基线**：四个方向全部安装 P05 直通模块。
- **B2 内部编码**：N=A短直通，E=B长折线，S=C短侧支，W=D折线+长侧支。

只有当 B2 相对 B1 在重定位测试中明显降低方向间相关性，才能把增量归因于内部形态，而不是仅仅归因于四个外部开口。
'''
(DOC/'README_中文.md').write_text(readme,encoding='utf-8')

print_bom='''# 打印清单、数量与硬件 BOM

## A. STL 打印数量

| 文件 | 数量 | 材料 | 打印方向 | 是否必须 |
|---|---:|---|---|:---:|
| P01_acoustic_base_tray.stl | 1 | PLA/PETG | 开放声道朝上 | 是 |
| P02_sealing_lid.stl | 1 | PLA/PETG | 大平面贴床，箭头朝上 | 是 |
| P03_mic_insert_*.stl | 选择 1 | PLA/PETG | 法兰贴床 | 是 |
| P04_port_plug_PRINT_4.stl | 4 | PLA/TPU | 法兰与拉片贴床，锥形轴朝上 | 是 |
| P05_module_straight_baseline_PRINT_4.stl | 4 | PLA/PETG | 薄底面贴床、槽朝上 | 是 |
| P06_module_A/B/C/D*.stl | 各 1 | PLA/PETG | 薄底面贴床、槽朝上 | 是 |
| P07_module_blocking_blank.stl | 1 | PLA/PETG | 任意平面 | 可选 |
| P08_module_fit_coupon.stl | 1 | 同主体 | 平底贴床 | 强烈推荐先打 |
| P09_module_fit_key.stl | 1 | 同模块 | 平底贴床 | 强烈推荐先打 |
| P10_mic_fit_gauge.stl | 1 | 同主体 | 平底贴床 | 推荐 |
| P11/P12 密封测试件 | 各 1 | PLA + TPU/垫片 | 平底贴床 | 推荐 |
| P13/P14 gasket | 各 1 | 85A–95A TPU | 平铺 | 可用切割垫替代 |
| P15_turntable_base* | 1 | PLA | 平底贴床 | 推荐 |
| P16_turntable_top* | 1 | PLA | 主平面贴床、立柱朝上 | 推荐 |
| P17/P18 pins | 各 1 | PLA/PETG | 轴线竖直 | 推荐 |

`PLATE_modules...` 和 `PLATE_small_parts.stl` 是便利打印板，不是新的零件；若打印板排布不适合你的机器，请使用独立 STL。

## B. 非打印硬件

- M3×18 或 M3×20 螺钉 12 个
- M3 螺母 12 个
- M3 平垫片 24 个（推荐）
- 0.8–1.0 mm 硅胶片或闭孔 EVA；也可打印 TPU gasket
- 少量可移除密封胶泥、PTFE 生料带或薄泡棉胶带
- 麦克风与线缆

## C. 推荐切片参数

- 材料：第一版优先 PLA
- 喷嘴：0.6 mm 优先；0.4 mm 也可
- 层高：0.28 mm（0.6 喷嘴）或 0.20–0.24 mm（0.4 喷嘴）
- 壁数：4
- 顶/底层：5–6
- 填充：15%；声学墙体由外轮廓形成，不依赖填充
- 支撑：所有零件均按无需支撑设计
- 主体 brim：5–8 mm

## D. 推荐打印顺序

1. P08、P09、P10 和 P11/P12 测试件。
2. 确认模块间隙与密封后打印 P01。
3. 检查 P01 全部通道贯通、无翘曲，再打印 P02。
4. 打印模块和插芯。
5. 最后打印旋转底座。
'''
(DOC/'PRINT_AND_BOM.md').write_text(print_bom,encoding='utf-8')

assembly='''# 装配说明

## 1. 打印后检查

1. 用 9 mm 左右圆棒或柔性通条检查四个固定通道。
2. 将 P09 依次插入 P08 的三档槽。三档从左到右为 0.1、0.25、0.4 mm/侧的名义长宽间隙。选择能够无明显晃动、又能拔出的设置来决定是否需要对模块 XY 缩放。
3. 用 P10 孔规检查实际插芯配合。四孔从左到右是 Ø19.8、20.0、20.2、20.4 mm。
4. 先组装 P11/P12 密封测试件，确认你的垫片与 M3 压紧方式不会明显漏气。

## 2. 麦克风插芯

- 底座中央孔 Ø20.4；插芯颈 Ø20.0。
- 插芯从底部插入，法兰作为轴向限位。
- 使用一圈 PTFE 生料带、薄 O 形圈或可移除胶泥密封。不要让胶进入中心腔。
- ID6、ID9.5、ID12.7 分别适配约 6、9.5、12.7 mm 外径探管或麦克风。空白版带 Ø2.5 pilot，可自行钻孔。
- 插入深度必须机械固定，并在所有实验中保持不变。

## 3. 模块安装与方向

模块右上角具有唯一斜切键，底座槽位具有同样键位。模块不能上下翻转；薄底面朝下、开放槽朝上。

B1：N/E/S/W 四槽全部使用 P05。

B2：

- N：A_short_straight
- E：B_long_serpentine
- S：C_straight_short_stub
- W：D_dogleg_long_stub

模块和槽每侧只有 0.2 mm 名义间隙。正式测量前，在模块外周使用极薄的可移除密封胶泥或泡棉条，避免周边间隙形成不受控侧腔。不要堵住模块两端声道。

## 4. 密封垫与上盖

- B1 使用 P13 的 NE/NW/SE/SW 四片，或 `gasket_B1_symmetric_1to1.svg`。
- B2 使用 P14 的 NE/NW/SE/SW 四片，或 `gasket_B2_encoded_1to1.svg`。
- 由于四条空气通道从中心一直切到外缘，密封面天然分成四个象限；四片式不是网格错误。
- SVG 是 1:1 mm 尺寸；打印/切割时必须关闭“适应页面”。
- 将垫片放在底座与模块上方，确认所有空气通道开口完全露出。
- 上盖北向箭头对准底座 +Y/N 方向。
- 12 个 M3 螺钉按对角交叉顺序逐步拧紧；只需压紧密封垫，不要把 PLA 上盖拧弯。

## 5. 入口堵头

P04 V1.0.1 是与 P01 渐缩入口相匹配的 12 mm 锥形堵头，不再是恒定截面的矩形轴。入口面处截面约 14.2×7.4 mm；10 mm 深处约 10.2×7.3 mm；最内侧带导入倒角的尖端约 9.2×6.8 mm。法兰约 23×14 mm，并带平面拉片。打印时法兰和拉片贴床、锥形轴朝上；装配时将窄端先插入入口。建议在法兰与 P01 外侧面之间放 0.5–1.0 mm 闭孔泡棉或薄硅胶作气密垫。不要对 P04 做统一 XY 缩放，因为那会同时改变插入轴长度方向以外的配合；若实测过紧，优先在切片器中只缩放截面 X/Y 0.5%，或轻磨尖端。堵头主要用于漏气诊断和单入口测量，不用于最终四方向开放实验。

## 6. 旋转底座

1. P17 中心轴从 P15 底部压入。
2. P16 套在中心轴上。
3. P18 穿过 P16 的单个定位孔并插入 P15 的八个定位孔之一，提供 45° 步进。
4. P16 的四个 Ø6.0 定位柱插入 P01 底部四个 Ø6.4、深 3.0 mm 的盲孔。
5. 四个支撑垫使 P01 底部与转盘主体保持 4 mm 间隙，给 M3 螺母、麦克风法兰和线缆留空间。
'''
(DOC/'ASSEMBLY.md').write_text(assembly,encoding='utf-8')

exp='''# 最小方向编码实验方案

## 1. 目标

检验内部非对称模块是否在四个外部入口布局不变的前提下，增加方向相关的频率谱形差异。

## 2. 三组对照

- B0：裸麦克风。
- B1：打印主体 + 四个相同直通模块。
- B2：同一打印主体 + A/B/C/D 四种不同模块。

B1 与 B2 必须使用同一个底座、同一个上盖、同一个麦克风插芯和同一套转接件，只更换小模块。

## 3. 测量布置

- 扬声器固定不动，声轴始终指向结构中心。
- 麦克风中心和结构旋转中心重合。
- 第一轮距离 1.0–1.5 m。
- 扬声器与麦克风中心等高。
- 结构尽量远离桌面和墙面。
- 使用 P15–P18 固定 0°、90°、180°、270°；可增加 45° 中间点。
- 使用已知 REW log sweep 或宽带白噪声。

## 4. 数据

每个结构状态和方向：

- 连续不拆装重复 5 次；
- 完全旋转离开再回到定位点 5 次；
- 随机化方向测试顺序。

优先分析 1.5–8 kHz；同时保留完整 300 Hz–10 kHz 原始数据。

## 5. 指标

1. 全频带均值去除后的谱形相关性。
2. 同方向重定位距离与异方向距离。
3. 方向相关性矩阵和有效秩。
4. 最近模板分类。
5. leave-one-reposition-session-out logistic regression。
6. 去掉总能量后是否仍能分类。

建议形态增益指标：

`G = median_between_direction_distance / median_within_direction_reposition_distance`

B2 的 G 应明显高于 B1；初步希望 G > 2。

## 6. 停止判据

若 B2 与 B1 差异不超过重定位误差，先不要打印复杂半球。依次检查：

- 入口是否过小或信号太弱；
- 1.5 kHz 以下是否占比过大；
- 模块周边是否漏气；
- 房间反射是否主导；
- 麦克风插入深度是否漂移；
- 外部入口是否缺乏方向选择性。

## 7. 模块公式说明

固定通道截面 9×8 mm，面积 72 mm²。A/C 模块主通道约 10×7 mm，面积 70 mm²，使截面积变化较小，优先让路径和侧支成为差异来源。

侧支粗略四分之一波长：`f≈c/(4L)`。

- C 侧支中心线约 25.5 mm：理想估计约 3.36 kHz。
- D 侧支中心线约 33.5 mm：理想估计约 2.56 kHz。

实际 notch/peak 会受 T 形连接、端部修正、损耗、入口辐射和中心腔耦合影响，因此这些值是设计中心，不是承诺频率。
'''
(DOC/'EXPERIMENT_PLAN.md').write_text(exp,encoding='utf-8')

handoff=f'''# AI / 新智能体交接文件

## 0. 任务背景

本项目从“多输入端口到单麦克风的内部声学网络”研究，转向一个更快的四方向 proof-of-concept：用四个朝向不同的外部入口和四个内部声学滤波模块，使中心单麦克风对已知宽带激励形成方向相关频率指纹。允许普通滤波器效应，目标是至少包含“结构先完成部分物理特征映射，数字端只做简单分类”的形态辅助计算。

参考基础：Sun et al. 2019/2020 的单麦克风 metamaterial enclosure。原论文使用三层随机半球、24 腔体、中心麦克风和方向相关 acoustic channel modules。V1 不是复刻；它把随机三维 ACM 简化为四个确定性的可换管道模块，以降低打印成本并增加消融可解释性。

## 1. 不可随意破坏的接口

所有尺寸单位 mm。权威参数在 `SOURCE/design_parameters_v1.json`。

- 底座最大跨度：210。
- 底座 z=0..10.4；固定通道地板 z=2.4，通道高 8.0。
- 模块槽：58.4×38.4×8.0。
- 模块体：58.0×38.0×8.0；每侧名义间隙 0.2。
- 模块局部坐标：长轴 X；X=-29 为中心腔侧，X=+29 为外部入口侧；右上角为 4 mm 键位斜切。
- 模块薄底 1.0，开放槽深 7.0。
- 中心麦克风孔：Ø20.4；插芯颈：Ø20.0。
- 上盖和底座的 12 个 M3 孔必须由同一 `SCREW_POS` 数组生成。
- 转盘立柱 Ø6.0，底座盲孔 Ø6.4、深 3.0；坐标为 (±24,±24)。

修改任一接口尺寸时，必须同步更新相关零件、JSON 和验证脚本。

## 2. 编码状态

B1：N/E/S/W 全为 A 直通模块。

B2：
- N=A，主路径 58 mm；
- E=B，折线主路径约 {module_metrics['E_B_long_serpentine']['main_centerline_mm']:.2f} mm；
- S=C，主路径 58 mm + 25.5 mm 闭端侧支；
- W=D，主路径约 {module_metrics['W_D_dogleg_long_stub']['main_centerline_mm']:.2f} mm + 33.5 mm 闭端侧支。

第一研究问题不是“哪个模块理论上最优”，而是同一主体中 B2 是否比 B1 增加跨重定位的方向可分性。

## 3. CAD 生成方法

`SOURCE/generate_package.py` 使用 Shapely 2D 几何和自定义分层 2.5D 网格生成器输出水密 STL。所有零件设计成平面分层结构，无需内部支撑。不要直接手改 STL；修改参数或几何后重新运行脚本，并检查 `validation_report.json`。

运行需求：Python 3.10+，numpy，shapely>=2.1，trimesh，matplotlib。

## 4. 自动验证要求

重新生成后至少确认：

- 每个独立零件 `is_watertight=True`；
- 模块高度等于槽深；
- 模块/槽、插芯/孔、立柱/盲孔均保持正间隙；
- 底座和上盖 M3 孔数量与坐标一致；
- 主体 X/Y 不超过目标打印床；
- B1/B2 gasket 的空气开口与对应模块槽一致；
- 组合打印板多组件是允许的，但独立 STL 是权威文件。

## 5. 已知风险

- 简单四通道不保证达到原论文的方向 coherence；这是快速风险验证件。
- 模块周边间隙可能形成微小寄生侧腔，必须使用可移除薄密封材料。
- P04 在 V1.0.1 已改为全深度锥形匹配；任何后续入口几何修改都必须同步重算 P04 的完整插入包络，不能只检查入口面宽度。
- FDM 上盖翘曲可能造成跨通道泄漏，先使用密封测试件。
- 小结构低频方向信息有限，优先 1.5–8 kHz。
- 方向差异可能同时来自外部开口和内部滤波，所以必须比较 B1 与 B2。
- 不要仅用随机训练/测试拆分；应按重定位 session 留一验证。

## 6. 下一版的正确调整方向

优先只改一个变量：

1. 外部入口尺寸/短导管长度；
2. 模块路径长度；
3. 侧支长度与颈宽；
4. 中心腔体积；
5. 增加一根可封堵内部桥；
6. 结构整体直径。

不要同时把外壳改成球体、增加大量随机孔并改变算法，否则无法知道增益来自哪里。
'''
(DOC/'AI_HANDOFF.md').write_text(handoff,encoding='utf-8')

ref='''# 设计依据与参考边界

## 主要参考

Xuecong Sun, Han Jia, Zhe Zhang, Yuzhen Yang, Zhaoyong Sun, Jun Yang, “Sound Localization and Separation in 3D Space Using a Single Microphone with a Metamaterial Enclosure,” Advanced Science, 7, 1902271. DOI: 10.1002/advs.201902271.

该论文的设计包含三层半球、随机孔和 24 个不同腔体；中心单麦克风接收经过方向相关外壳调制的信号。论文把不同方向的结构看成不同 acoustic channel modules，并说明几何参数会决定频率响应。本设计只继承“被动结构提供方向相关频谱指纹”的框架，不复制其多声源压缩感知任务。

## 次要参考概念

Soft Proprioception in the Frequency Domain via Tube Resonance 使用管道边界条件和音孔产生频域指纹，并表明简单线性分类器可利用部分由形态产生的可分特征。本设计中的闭端 stub 采用相同的四分之一波长直觉，但不是柔性 slit 传感器。

## 明确不受来源支持、属于工程推断的部分

- V1 的具体 210 mm 尺寸、四通道数量、模块路径和 1.5–8 kHz 建议是为低成本 FDM proof-of-concept 做的工程选择，不是原论文的优化参数。
- 侧支估计采用理想 `f=c/(4L)`，实际频率必须实验校准。
- 预计 B2 优于 B1 是待验证假设，不是已知结论。
'''
(DOC/'DESIGN_BASIS.md').write_text(ref,encoding='utf-8')

# Copy generator itself into source package.
this_path=Path(__file__)
(SRC/'generate_package.py').write_text(this_path.read_text(encoding='utf-8'),encoding='utf-8')
(SRC/'requirements.txt').write_text('numpy\nshapely>=2.1\ntrimesh\nmatplotlib\n',encoding='utf-8')

(STL/'README_UNITS_MM.txt').write_text('All STL coordinates are in millimetres. Do not import as inches.\n',encoding='utf-8')


(OUT/'START_HERE.txt').write_text('''Acoustic Morphology Encoder V1.0.1

1) Read DOCS/README_中文.md
2) Print P08/P09/P10/P11/P12 coupons first
3) Read DOCS/ASSEMBLY.md before printing the large base
4) Individual STL files are authoritative; PLATE files are only convenience layouts
5) All dimensions are millimetres
''',encoding='utf-8')
(DOC/'CHANGELOG.md').write_text('''# Changelog

## 1.0.1
- Corrected P04: replaced the constant-width rectangular shaft with a 12 mm tapered plug that follows the P01 outer-port envelope.
- Added full-depth insertion-envelope validation; the previous check only compared the plug width with the outer mouth width.
- Changed P04 to a support-free flange-down print orientation with a planar pull tab.

## 1.0.0
- Initial modular four-direction acoustic morphology encoder.
- Added B1 symmetric and B2 encoded module sets.
- Added four-piece gaskets, fit coupons, indexed turntable, source generator, and automated mesh/assembly validation.
''',encoding='utf-8')
(OUT/'LICENSE_AND_DISCLAIMER.txt').write_text('''Generated research prototype files are provided for experimental use and modification. No performance, safety, acoustic isolation, or fitness-for-purpose warranty is made. Verify clearances on your printer with the included coupons before committing to the large parts. The cited Sun et al. paper is not redistributed in this package; consult the original open-access article and cite it independently.
''',encoding='utf-8')

# BOM CSV and file manifest.
import csv, hashlib
bom_rows=[
    ['P01_acoustic_base_tray.stl',1,'PLA','required'],
    ['P02_sealing_lid.stl',1,'PLA','required'],
    ['P03_mic_insert_*.stl',1,'PLA','choose one'],
    ['P04_port_plug_PRINT_4.stl',4,'PLA/TPU','required for diagnostics'],
    ['P05_module_straight_baseline_PRINT_4.stl',4,'PLA','required B1'],
    ['P06_module_A_short_straight.stl',1,'PLA','required B2 N'],
    ['P06_module_B_long_serpentine.stl',1,'PLA','required B2 E'],
    ['P06_module_C_straight_short_stub.stl',1,'PLA','required B2 S'],
    ['P06_module_D_dogleg_long_stub.stl',1,'PLA','required B2 W'],
    ['P13_gasket_B1_symmetric_4piece_TPU.stl',1,'TPU/cut sheet','required B1'],
    ['P14_gasket_B2_encoded_4piece_TPU.stl',1,'TPU/cut sheet','required B2'],
    ['P15-P18 turntable parts',1,'PLA','recommended'],
]
with open(DOC/'BOM.csv','w',newline='',encoding='utf-8-sig') as f:
    w=csv.writer(f); w.writerow(['file_or_group','quantity','material','role']); w.writerows(bom_rows)

manifest=[]
for p in sorted(OUT.rglob('*')):
    if p.is_file():
        data=p.read_bytes(); manifest.append({'path':str(p.relative_to(OUT)),'bytes':len(data),'sha256':hashlib.sha256(data).hexdigest()})
(OUT/'MANIFEST.json').write_text(json.dumps({'package':'Acoustic_Morphology_Encoder_V1','version':P['version'],'files':manifest},indent=2,ensure_ascii=False),encoding='utf-8')

print(f'Generated package at {OUT}')
print(f'STL count: {len(list(STL.glob("*.stl")))}')
print('Independent all watertight:', report['all_individual_parts_watertight'])
for c in checks:
    if not c['pass']:
        print('FAILED CHECK',c)
