"""Build the additive FAST-B1 pre-release freeze package without authority reads."""
from __future__ import annotations

import hashlib
import json
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
OUT = REPO / "outputs/gen_enc/GEN_ENC_FAST_START/b1_preexecution_freeze"
TASK = "01a049a7-15ca-79e1-92a2-d3822ba8609d"
INTERMEDIATE = "01a0452b-ee9f-7ce0-a671-78d80cb069fe"
ADVISOR_B = "01a04992-e6d1-7d50-b85a-9e58e35fcaec"
GUARDIAN = "01a04498-2cb6-7073-9e02-943dd8ec7bba"
TOP = "01a0366d-bb5e-7a13-a1f7-b34403664543"
ALLOWLIST = "outputs/gen_enc/GEN_ENC_FAST_START/fast_0_authority_batch_contract_freeze/authority_allowlist.json"
ALLOWLIST_SHA = "49263e3cab9825840284d18a4d628be73d1273bf6940493878bac5da529c958c"
REVIEW = "outputs/governance/RESEARCH_SCOPE_CONTRACTION_AUDIT/reviews/GEN_ENC_FAST_0_AUTHORITY_BATCH_CONTRACT_FREEZE_PREEXECUTION_REVIEW.json"
REVIEW_SHA = "f96a71e850ceaefa9c2267c2641d6307c9c98af38b53aa8ef3893fef5de2c8fd"


def sha(path: Path) -> str: return hashlib.sha256(path.read_bytes()).hexdigest()


def write(name: str, value: object) -> None:
    path = OUT / name; path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(value, ensure_ascii=False, indent=2) + "\n", encoding="utf-8", newline="\n")


def file_entries(paths: list[str]) -> list[dict[str, object]]:
    return [{"path": path, "sha256": sha(REPO / path), "bytes": (REPO / path).stat().st_size} for path in paths]


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    allowlist = json.loads((REPO / ALLOWLIST).read_text(encoding="utf-8"))
    if sha(REPO / ALLOWLIST) != ALLOWLIST_SHA or sha(REPO / REVIEW) != REVIEW_SHA: raise RuntimeError("UPSTREAM_HASH")
    source_paths = ["scripts/gen_enc_b1/__init__.py", "scripts/gen_enc_b1/formal_driver.py", "scripts/gen_enc_b1/independent_verifier.py", "scripts/gen_enc_b1/build_freeze.py"]
    schema_paths = [p.relative_to(REPO).as_posix() for p in sorted((REPO / "schemas/gen_enc/b1").glob("*.json"))]
    commands = [
        ["python", "-m", "scripts.gen_enc_b1.formal_driver", "preflight", "--repo-root", ".", "--release", "outputs/gen_enc/GEN_ENC_FAST_START/b1_release_control/RELEASE.json", "--guardian-attestation", "outputs/gen_enc/GEN_ENC_FAST_START/b1_release_control/GUARDIAN_ATTESTATION.json", "--schema-root", "schemas/gen_enc/b1"],
        ["python", "-m", "scripts.gen_enc_b1.formal_driver", "generate-staging", "--repo-root", ".", "--release", "outputs/gen_enc/GEN_ENC_FAST_START/b1_release_control/RELEASE.json", "--guardian-attestation", "outputs/gen_enc/GEN_ENC_FAST_START/b1_release_control/GUARDIAN_ATTESTATION.json", "--schema-root", "schemas/gen_enc/b1"],
        ["python", "-m", "scripts.gen_enc_b1.independent_verifier", "verify", "--repo-root", ".", "--release", "outputs/gen_enc/GEN_ENC_FAST_START/b1_release_control/RELEASE.json", "--guardian-attestation", "outputs/gen_enc/GEN_ENC_FAST_START/b1_release_control/GUARDIAN_ATTESTATION.json", "--schema-root", "schemas/gen_enc/b1"],
        ["python", "-m", "scripts.gen_enc_b1.formal_driver", "publish", "--repo-root", ".", "--release", "outputs/gen_enc/GEN_ENC_FAST_START/b1_release_control/RELEASE.json", "--guardian-attestation", "outputs/gen_enc/GEN_ENC_FAST_START/b1_release_control/GUARDIAN_ATTESTATION.json", "--schema-root", "schemas/gen_enc/b1"],
        ["python", "-m", "scripts.gen_enc_b1.formal_driver", "recover", "--repo-root", ".", "--release", "outputs/gen_enc/GEN_ENC_FAST_START/b1_release_control/RELEASE.json", "--guardian-attestation", "outputs/gen_enc/GEN_ENC_FAST_START/b1_release_control/GUARDIAN_ATTESTATION.json", "--schema-root", "schemas/gen_enc/b1"],
        ["python", "-m", "scripts.gen_enc_b1.formal_driver", "package-results", "--repo-root", ".", "--release", "outputs/gen_enc/GEN_ENC_FAST_START/b1_release_control/RELEASE.json", "--guardian-attestation", "outputs/gen_enc/GEN_ENC_FAST_START/b1_release_control/GUARDIAN_ATTESTATION.json", "--schema-root", "schemas/gen_enc/b1"]
    ]
    write("source_manifest.json", {"schema_version": "gen_enc_fast_b1_source_manifest_v1", "task_id": TASK, "files": file_entries(source_paths), "driver_and_verifier_import_each_other": False, "formal_technical_fixture_import_count": 0, "authority_read_count": 0, "final_test_read": False})
    write("schema_manifest.json", {"schema_version": "gen_enc_fast_b1_schema_manifest_v1", "task_id": TASK, "files": file_entries(schema_paths), "schema_count": len(schema_paths), "all_top_level_additional_properties_false": True, "authority_read_count": 0, "final_test_read": False})
    write("command_manifest.json", {"schema_version": "gen_enc_fast_b1_command_manifest_v1", "task_id": TASK, "batch_id": "B1", "commands_exact": ["preflight", "generate-staging", "verify", "publish", "recover", "package-results"], "argv_exact": commands, "hidden_alias_count": 0, "release_must_bind_this_manifest_sha256": True, "authority_read_count": 0, "final_test_read": False})
    source_sha, schema_sha, command_sha = (sha(OUT / x) for x in ("source_manifest.json", "schema_manifest.json", "command_manifest.json"))
    members = [{"family_id": family, "member_id": f"{prefix}_{i:02d}", "slot_ordinal": i, "failure_slot_retained": True} for family, prefix in zip(("HAND_DESIGNED", "NEAR_INDEPENDENT", "FIXED_SEED_RANDOM_DISORDERED", "PHYSICS_METAMATERIAL_INSPIRED"), ("HAND", "NEAR", "RANDOM", "PHYSICS")) for i in range(1, 6)]
    write("b1_member_ledger.json", {"schema_version": "gen_enc_fast_b1_member_ledger_v1", "task_id": TASK, "batch_id": "B1", "selection_rule": "FROZEN_ORDINAL_01_TO_05_NO_REDRAW_REPAIR_REPLACEMENT_REORDER_RESULT_FILTER", "members": members, "member_count": 20, "failed_slots_retained": True, "formal_execution_started": False, "authority_read_count": 0, "final_test_read": False})
    write("authority_binding.json", {"schema_version": "gen_enc_fast_b1_authority_binding_v1", "task_id": TASK, "source_allowlist_path": ALLOWLIST, "source_allowlist_sha256": ALLOWLIST_SHA, "matching_rule": allowlist["matching_rule"], "entry_count": allowlist["entry_count"], "triples": [{"purpose": x["purpose"], "path": x["path"], "sha256": x["sha256"], "pointer": x["pointer"], "object_shape": x["object_shape"]} for x in allowlist["entries"]], "technical_fixture_count": 0, "arbitrary_triple_allowed": False, "formal_authority_content_read": False, "authority_read_count": 0, "final_test_read": False})
    fixture_paths = ["tests/fixtures/gen_enc_b1/technical_contract_fixture.json", "tests/test_gen_enc_b1_preexecution_freeze.py"]
    write("fixture_manifest.json", {"schema_version": "gen_enc_fast_b1_fixture_manifest_v1", "task_id": TASK, "identity_class": "TECHNICAL_FIXTURE_ONLY_NEVER_FORMAL_AUTHORITY", "files": file_entries(fixture_paths), "formal_cli_import_count": 0, "formal_allowlist_membership": False, "formal_authority_read_count": 0, "final_test_read": False})
    document_paths = ["docs/experiment/gen_enc/GEN_ENC_FAST_B1_PREEXECUTION_EXECUTABLE_FREEZE_ADDENDUM.md", "docs/progress/GEN_ENC_FAST_B1_PREEXECUTION_EXECUTABLE_FREEZE_RESULTS.md"]
    write("document_manifest.json", {"schema_version": "gen_enc_fast_b1_document_manifest_v1", "task_id": TASK, "files": file_entries(document_paths), "additive_only": True, "upstream_modified": False, "final_test_read": False})
    write("artifact_contract.json", {"schema_version": "gen_enc_fast_b1_artifact_contract_v1", "task_id": TASK, "batch_id": "B1", "immutable_run_artifacts": {"member_identities_with_complete_cad_static": 20, "partial_family_manifests": 4, "batch_index": 1, "static_audit": 1, "independent_verification": 1, "sha256sums": 1, "generation_terminal": 1, "verifier_terminal": 1, "publication_terminal": 1, "total": 31}, "external_commit_pointer": 1, "external_package_terminal_exactly_one": 1, "zero_unlisted": True, "driver_staging_success_eligible": False, "verifier_reseal_required": True, "commit_pointer_after_all_31_targets": True, "package_terminal_after_commit_pointer": True, "batch_is_final80_or92": False, "final_test_read": False})
    write("release_blueprint_not_release.json", {"schema_version": "gen_enc_fast_b1_release_blueprint_v1", "record_kind": "NONAUTHORITATIVE_BLUEPRINT_NOT_RELEASE", "task_id": TASK, "batch_id": "B1", "future_record_kind": "RELEASE_NEW_CANONICAL_BYTES_ONLY_AT_SIGNING", "future_release_path": "outputs/gen_enc/GEN_ENC_FAST_START/b1_release_control/RELEASE.json", "future_attestation_path": "outputs/gen_enc/GEN_ENC_FAST_START/b1_release_control/GUARDIAN_ATTESTATION.json", "run_id_derivation": "sha256(b'GEN-ENC-FAST-B1-RUN-ID-v1\\n' + canonical_json(release_with_run_id_64_zeroes))", "binds": ["task", "batch", "run", "authority_triples", "source_manifest", "schema_manifest", "command_manifest", "mode", "roots", "expiry", "revocation", "consumption"], "one_use": True, "issued_consumed_revoked_immutable_side_records": True, "release_created": False, "attestation_created": False, "authority_read_count": 0, "final_test_read": False})
    write("root_and_transaction_contract.json", {"schema_version": "gen_enc_fast_b1_root_transaction_contract_v1", "task_id": TASK, "root_templates": {name: f"outputs/gen_enc/GEN_ENC_FAST_START/b1_runs/{{run_id}}/{name}" for name in ("staging", "run", "journal", "success", "failure", "side_records") } | {"pointer": "outputs/gen_enc/GEN_ENC_FAST_START/b1_commit_pointers/{run_id}"}, "mutually_exclusive": True, "target_count": 31, "durable_intent_before_each_replace": True, "exact_temp": ".{target_name}.{run_id}.{target_index_02d}.b1.tmp", "ownership_token_recomputed_before_delete": True, "containment_and_reparse_rechecked_before_delete": True, "journal_boolean_or_filename_substring_trusted": False, "real_subprocess_kill_after_replace_before_journal_test_targets": 20, "cross_root_commit_pointer": True, "zero_partial_publication_after_failure": True, "final_test_read": False})
    all_false = {name: False for name in ("authority_read", "identity_generation", "static_audit", "publication", "timing", "response", "performance", "comparison", "ranking", "selection", "optimization", "matched_cost", "direction", "no_improvement", "simulation", "full_wave", "physical", "final80", "final92", "final_test_read")}
    write("DRAFT.json", {"schema_version": "gen_enc_fast_b1_draft_v1", "record_kind": "DRAFT", "authoritative": False, "non_authoritative": True, "attempt": 0, "task_id": TASK, "batch_id": "B1", "run_id": None, "permissions": all_false, "may_flip_or_promote": False, "future_release_must_be_new_canonical_bytes": True})
    write("execution_state.json", {"schema_version": "gen_enc_fast_b1_execution_state_v1", "task_id": TASK, "status": "PRE_RELEASE_FREEZE_ONLY_FORMAL_EXECUTION_BLOCKED", "formal_authority_read_count": 0, "formal_member_count": 0, "formal_static_run_count": 0, "formal_publication_count": 0, "release_created": 0, "attestation_created": 0, "commit_pointer_created": 0, "package_success_created": 0, "scientific_hypothesis_status": "NOT_TESTED", "final_test_read": False})
    write("governance_bindings.json", {"schema_version": "gen_enc_fast_b1_governance_bindings_v1", "task_id": TASK, "intermediate_controller_task_id": INTERMEDIATE, "advisor_b_task_id": ADVISOR_B, "guardian_task_id": GUARDIAN, "top_level_task_id": TOP, "sole_current_guardian_authority": {"path": REVIEW, "sha256": REVIEW_SHA, "verdict": "ACCEPT"}, "advisor_b_review_path": "outputs/governance/RESEARCH_ADVANCEMENT_SCOPE_INTEGRITY_ADVISOR/reviews/GEN_ENC_FAST_START_BATCH_PROPOSAL_REVIEW.json", "advisor_b_review_sha256": "438a16cf7b588083ac4524f1dfcd435b27ef50676334dddc2dbfb44aa4f8c02d", "stage_integrity_ledger_path": "outputs/governance/RESEARCH_ADVANCEMENT_SCOPE_INTEGRITY_ADVISOR/stage_integrity_ledger.json", "stage_integrity_ledger_sha256": "97c133db149b9c9b2353edb288541943e71e3fe66fbfe4537438b36ca4d287c5", "release_authorized_now": False, "formal_execution_authorized_now": False, "final_test_read": False})
    write("claim_ceiling.json", {"schema_version": "gen_enc_fast_b1_claim_ceiling_v1", "allowed": ["batch-local identity provenance for exact 20 slots", "complete member-local CAD/static status", "batch-local technical validity", "independent verification"], "forbidden": ["family or global claim", "cross-family comparison", "performance", "matched-cost superiority", "direction readability", "NO_IMPROVEMENT", "timing", "full-wave", "physical claim", "final80", "final92"], "failed_slots_retained": True, "scientific_hypothesis_status": "NOT_TESTED", "final_test_read": False})
    write("tests_history.json", {"schema_version": "gen_enc_fast_b1_tests_history_v1", "task_id": TASK, "runs": [{"run": "run01", "command": "python -m pytest tests/test_gen_enc_b1_preexecution_freeze.py -q --basetemp=.t/b1_freeze_run01", "result": "38_failed_4_passed", "finding": "release.schema.json missing one object-closing brace; all downstream setup failures retained", "formal_effect": "NONE"}, {"run": "run02", "command": "python -m pytest tests/test_gen_enc_b1_preexecution_freeze.py -q --basetemp=.t/b1_freeze_run02", "result": "42_passed_in_14.49s", "formal_effect": "NONE"}, {"run": "run03", "command": "python -m pytest tests/test_gen_enc_b1_preexecution_freeze.py -q --basetemp=.t/b1_freeze_run03", "result": "43_passed_in_14.22s", "formal_effect": "NONE"}, {"run": "run04", "command": "python -m pytest tests/test_gen_enc_b1_preexecution_freeze.py -q --basetemp=.t/b1_freeze_run04", "result": "43_passed_in_15.45s", "formal_effect": "NONE"}, {"run": "run05", "command": "python -m pytest tests/test_gen_enc_b1_preexecution_freeze.py -q --basetemp=.t/b1_freeze_run05", "result": "44_passed_in_14.87s", "formal_effect": "NONE"}], "coverage": ["exact 20 fixed members", "independent named-axis and seed validation", "RANDOM binary64 nextafter", "PHYSICS Fisher-Yates midpoint LHS", "complete CAD witness rejection", "strict schemas and zero-unlisted cardinality", "20 real subprocess crash targets", "copy/fsync/replace/journal/pointer/terminal faults", "cross-root pointer", "mixed-terminal prevention", "run-id derivation", "freeze-package SHA256SUMS and DRAFT/counter audit"], "formal_authority_read_count": 0, "formal_member_count": 0, "final_test_read": False})
    write("final_test_run.json", {"schema_version": "gen_enc_fast_b1_final_test_run_v1", "task_id": TASK, "run": "run06", "command": "python -m pytest tests/test_gen_enc_b1_preexecution_freeze.py -q --basetemp=.t/b1_freeze_run06", "result": "44_passed_in_15.42s", "additional_hardening": ["formal publish requires schema-valid independent PASS and exact 30-entry resealed hashes", "preflight operational roots must be new", "recovery derives every exact target instead of trusting journal names", "independent formal gate hashes source/schema/command manifests and validates consumption binding"], "formal_authority_read_count": 0, "formal_member_count": 0, "formal_static_run_count": 0, "formal_publication_count": 0, "final_test_read": False})
    residue = []
    for base in (REPO / ".t",):
        if base.exists():
            for path in sorted(base.glob("b1_*")):
                if path.exists(): residue.append({"path": path.relative_to(REPO).as_posix(), "is_directory": path.is_dir()})
    write("temporary_residue_inventory.json", {"schema_version": "gen_enc_fast_b1_temp_residue_v1", "task_id": TASK, "cleanup_authorized": False, "cleanup_performed": False, "entries": residue, "entry_count": len(residue), "final_test_read": False})
    write("final_readonly_audit.json", {"schema_version": "gen_enc_fast_b1_final_readonly_audit_v1", "task_id": TASK, "status": "READY_FOR_INTERMEDIATE_AND_ADVISOR_B_REVIEW_FORMAL_EXECUTION_BLOCKED", "source_manifest_sha256": source_sha, "schema_manifest_sha256": schema_sha, "command_manifest_sha256": command_sha, "authority_allowlist_sha256": ALLOWLIST_SHA, "guardian_review_sha256": REVIEW_SHA, "formal_authority_read_count": 0, "formal_member_count": 0, "formal_static_run_count": 0, "formal_publication_count": 0, "release_created": False, "attestation_created": False, "commit_pointer_created": False, "final_test_read": False})
    files = sorted(p for p in OUT.rglob("*") if p.is_file() and p.name != "SHA256SUMS.txt")
    (OUT / "SHA256SUMS.txt").write_text("".join(f"{sha(p)}  {p.relative_to(OUT).as_posix()}\n" for p in files), encoding="ascii", newline="\n")


if __name__ == "__main__": main()
