from __future__ import annotations
import hashlib,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];TASK="01a049a7-15ca-79e1-92a2-d3822ba8609d";PACKAGE=ROOT/"outputs/gen_enc/GEN_ENC_FAST_START/b1_real_shape_mapping_adapter_freeze_01";SCHEMAS=ROOT/"schemas/gen_enc/b1_mapping_adapter_01"
COLLECTOR="outputs/gen_enc/GEN_ENC_FAST_START/b1_repair_11_shape_collector_02_runs/43d7697d898aaab532e295cc848acfac8df4c19bdd35eb0a1e64097779e27627/shape_mapping.json"
GUARDIAN_REVIEW="outputs/governance/RESEARCH_SCOPE_CONTRACTION_AUDIT/reviews/GEN_ENC_FAST_B1_R11_GEOMETRY_SLOT_Z_FULL_INTERVAL_SEMANTIC_DISPOSITION.json"
DEPS={"NUMERIC_IDENTITY":"outputs/gen_enc/GEN_ENC_2A_NUMERIC_CONTRACT_PROPOSAL_REV01/family_identity_manifest_rev01.json","CAD0_MULTI_SOURCE_02":"outputs/gen_enc/GEN_ENC_CAD_0_FIXED_SECTOR_MAPPING_CONTRACT/phase_a_rev01/corrected_geometry_and_z_contract.json","CAD0_MULTI_SOURCE_03":"outputs/gen_enc/GEN_ENC_CAD_0_FIXED_SECTOR_MAPPING_CONTRACT/phase_a_rev01/ownership_and_algorithms.json","CAD0_MULTI_SOURCE_05":"outputs/gen_enc/GEN_ENC_CAD_0_FIXED_SECTOR_MAPPING_CONTRACT/phase_a_rev01/slot_ledger.json","CAD0_MULTI_SOURCE_07":"outputs/gen_enc/GEN_ENC_CAD_0_FIXED_SECTOR_MAPPING_CONTRACT/phase_a_rev01/connectivity_disclosure_metrics.json","CAD0_MULTI_SOURCE_10":"outputs/gen_enc/GEN_ENC_CAD_0_FIXED_SECTOR_MAPPING_CONTRACT/phase_a_rev02/constrained_root_proof.json","CAD0_MULTI_SOURCE_11":"outputs/gen_enc/GEN_ENC_CAD_0_FIXED_SECTOR_MAPPING_CONTRACT/phase_a_rev02/interface_exception_contract.json"}
def canon(v):return (json.dumps(v,sort_keys=True,separators=(",",":"),ensure_ascii=False)+"\n").encode()
def write(p,v):p.parent.mkdir(parents=True,exist_ok=True);p.write_bytes(canon(v))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def build():
    members=[f"{family}_{i:02d}" for family in ("HAND","NEAR","RANDOM","PHYSICS") for i in range(1,6)];PACKAGE.mkdir(parents=True,exist_ok=True)
    adapter={"schema_version":"gen_enc_b1_real_shape_mapping_adapter_contract_v1","record_kind":"SINGLE_ADDITIVE_REAL_SHAPE_MAPPING_ADAPTER","task_id":TASK,"members":members,"member_count":20,"families":["HAND","NEAR","RANDOM","PHYSICS"],"geometry_volume":{"field":"GEOMETRY_VOLUME","source_id":"NUMERIC_IDENTITY","pointer":"/common_connected_volume_and_cad_mapping/target_m3"},"geometry_target_fraction":{"field":"GEOMETRY_TARGET_FRACTION","source_id":"NUMERIC_IDENTITY","pointer":"/common_connected_volume_and_cad_mapping/central_share","cross_check_source_id":"CAD0_MULTI_SOURCE_02","cross_check_pointer":"/central/union_volume_formula"},"geometry_slot_z":{"replacement_field":"GEOMETRY_SLOT_Z_INTERVAL_M","type":"array","min_items":2,"max_items":2,"primary":{"source_id":"CAD0_MULTI_SOURCE_02","pointer":"/sector/collector/z_m"},"per_slot":{"source_id":"CAD0_MULTI_SOURCE_05","pointers":{n:"/slots/"+n+"/z_m" for n in ("SPINE","WINDOW_1","WINDOW_2","WINDOW_3","OUTER_1")}},"old_scalar_expectation":"SUPERSEDED_BY_AUTHORITY_SHAPE_CORRECTION","forbidden_inputs":["/target/scientific_lane_z_intervals_m"],"midpoint_policy":"NON_AUTHORITATIVE_OPTIONAL_LOG_ONLY_EXCLUDED_FROM_STATIC_IDENTITY_HASH_METRICS_ELIGIBILITY_RANKING_SCIENCE"},"interval_native_static_rules":{"finite_ordered_endpoints":True,"containment":"child_min>=container_min and child_max<=container_max","non_empty_overlap":"max(left_min,right_min)<min(left_max,right_max)","thickness_or_clearance":"upper_endpoint-lower_endpoint","midpoint_lower_upper_as_decision_inputs":False},"type_corrections":{"ROOT_BRACKET":{"pointer":"/root_bracket","type":"object"},"SLOT_ROWS":{"pointer":"/slots","type":"object"},"U4_PARTICIPATION":{"pointer":"/participation","type":"object"},"ZERO_EDGE_RULE":{"pointer":"/later_summary_rule","type":"string"}},"ownership":{"OWNERSHIP_CELLS":"DERIVE_FIVE_PER_MEMBER_FROM_TRANSFORMS_SECTOR_ORDER_AND_OWNERSHIP_ALGORITHM","OWNERSHIP_RULE":"BIND_EXISTING_OWNERSHIP_ALGORITHM_FIELDS","source_id":"CAD0_MULTI_SOURCE_03","transforms_pointer":"/transforms","algorithm_pointer":"/ownership","witness_count_per_member":5,"witness_count_b1":100},"threshold_metric_evidence_change":False,"identity_or_static_execution":False,"final_test_read":False};write(PACKAGE/"adapter_contract.json",adapter)
    dependency={"schema_version":"gen_enc_b1_real_shape_adapter_dependencies_v1","task_id":TASK,"collector_mapping":{"path":COLLECTOR,"sha256":sha(ROOT/COLLECTOR),"mapping_digest":"b0c614a5d55e9268bbcc25961a130616485fee7d6f08fe76c7c3925cbf195c55"},"sources":[{"source_id":k,"path":v,"sha256":sha(ROOT/v),"read_only":True} for k,v in DEPS.items()],"final_test_read":False};write(PACKAGE/"dependency_table.json",dependency)
    schema={"$schema":"https://json-schema.org/draft/2020-12/schema","type":"object","additionalProperties":False,"required":list(adapter.keys()),"properties":{k:{"const":v} for k,v in adapter.items()}};write(SCHEMAS/"adapter_contract.schema.json",schema)
    sources=["scripts/gen_enc_b1_mapping_adapter_01/driver_adapter.py","scripts/gen_enc_b1_mapping_adapter_01/verifier_adapter.py","scripts/gen_enc_b1_mapping_adapter_01/build_freeze_package.py","tests/test_gen_enc_b1_mapping_adapter_01.py"];write(PACKAGE/"source_manifest.json",{"record_kind":"SOURCE_MANIFEST","task_id":TASK,"files":[{"path":p,"sha256":sha(ROOT/p)} for p in sources]});write(PACKAGE/"schema_manifest.json",{"record_kind":"SCHEMA_MANIFEST","task_id":TASK,"files":[{"path":p.relative_to(ROOT).as_posix(),"sha256":sha(p)} for p in sorted(SCHEMAS.glob("*.json"))]});write(PACKAGE/"command_manifest.json",{"record_kind":"ADAPTER_FREEZE_COMMAND_MANIFEST","task_id":TASK,"commands":[],"formal_execution_authorized":False,"next_stage":"CONTROLLER_SCHEDULED_SINGLE_PROCESS_B1_EXACT20_AFTER_LIGHTWEIGHT_ACCEPTANCE","final_test_read":False});write(PACKAGE/"provenance.json",{"record_kind":"ONE_SHOT_REAL_SHAPE_MAPPING_ADAPTER_PROVENANCE","task_id":TASK,"collector_mapping_sha256":sha(ROOT/COLLECTOR),"guardian_full_interval_disposition":{"path":GUARDIAN_REVIEW,"sha256":sha(ROOT/GUARDIAN_REVIEW)},"old_scalar_slot_z":"SUPERSEDED_NOT_MODIFIED","adapter_modification_count":1,"formal_identity_count":0,"formal_static_count":0,"formal_science_count":0,"final_test_read":False});write(PACKAGE/"DRAFT.json",{"record_kind":"DRAFT_NOT_EXECUTION","task_id":TASK,"run_id":None,"identity":False,"static":False,"simulation":False,"publication":False,"final_test_read":False});write(PACKAGE/"test_history.json",{"record_kind":"TEST_HISTORY","runs":[{"result":"3_PASSED","duration_seconds":0.15}],"real_read_only_conformance":True,"formal_identity_count":0,"formal_static_count":0,"final_test_read":False})
    files=sorted(p for p in PACKAGE.glob("*.json") if p.name!="SHA256SUMS.json");write(PACKAGE/"SHA256SUMS.json",{"record_kind":"SHA256SUMS","files":[{"path":p.name,"sha256":sha(p)} for p in files]})
if __name__=="__main__":build()
