import com.comsol.model.*;import com.comsol.model.util.*;import java.util.*;
public class GenEnc31PrintTolA{
 static final String ROOT="D:/Bristol course/dissertation/program work/",BASE=ROOT+"outputs/gen_enc/GEN_ENC_9_LOSS_3D_BRIDGE/NEAR_01_lossy3d_eta0p02_size1.mph",OUT=ROOT+"scripts/gen_enc_31_print_tol_a/run_output/";static final double HALF=.0362053299278368/2,TH=.0092;
 static double vol(double f){return 8e-6*343*343/(.012*Math.pow(2*Math.PI*f,2));}
 static String geom(Model m,double f,double len,double ascale,double vscale){GeomSequence g=m.component("comp1").geom("geom1");double vn=vol(f),side=Math.sqrt(vn/(4*TH)),sx=.002*Math.sqrt(ascale),sy=.004*Math.sqrt(ascale);String[] tags={"tne","tnw","tsw","tse"};double[][] pos={{HALF-side,HALF-side,0},{-HALF,HALF-side,0},{-HALF,-HALF,0},{HALF-side,-HALF,0}};for(int i=0;i<4;i++){g.feature().create(tags[i],"Block");g.feature(tags[i]).set("size",new double[]{side,side,TH});g.feature(tags[i]).set("pos",pos[i]);}g.feature().create("tplenum","Difference");g.feature("tplenum").selection("input").set(new String[]{"plenum"});g.feature("tplenum").selection("input2").set(tags);g.feature("tplenum").set("selresult","on");g.feature().create("tneck","Block");g.feature("tneck").set("size",new double[]{sx,sy,len});g.feature("tneck").set("pos",new double[]{.012-sx/2,-sy/2,TH});g.feature("tneck").set("selresult","on");g.feature().create("tcavity","Block");g.feature("tcavity").set("size",new double[]{.017,.017,vn*vscale/(.017*.017)});g.feature("tcavity").set("pos",new double[]{.0035,-.0085,TH+len});g.feature("tcavity").set("selresult","on");g.run();m.param().set("tol_sx",Double.toString(sx));m.param().set("tol_sy",Double.toString(sy));return "geom1_tneck_dom";}
 static void setup(Model m,String neck){ModelNode c=m.component("comp1");String[] p={"nv0","nv90","nv180","nv270"},s={"port0_face","port90_face","port180_face","port270_face"};for(int i=0;i<4;i++)c.physics("acpr").feature(p[i]).selection().named(s[i]);c.physics("acpr").feature().create("tnra","NarrowRegionAcousticsModel",3);c.physics("acpr").feature("tnra").selection().named(neck);c.physics("acpr").feature("tnra").set("DuctType","RectangularDuct");c.physics("acpr").feature("tnra").set("a_rect","tol_sx");c.physics("acpr").feature("tnra").set("b_rect","tol_sy");c.physics("acpr").feature("tnra").set("rho_mat","userdef");c.physics("acpr").feature("tnra").set("rho","1.204[kg/m^3]");c.physics("acpr").feature("tnra").set("c_mat","userdef");c.physics("acpr").feature("tnra").set("c","343[m/s]");c.physics("acpr").feature("tnra").set("mu_mat","userdef");c.physics("acpr").feature("tnra").set("mu","1.814e-5[Pa*s]");c.physics("acpr").feature("tnra").set("kcond_mat","userdef");c.physics("acpr").feature("tnra").set("kcond",".0257[W/(m*K)]");c.physics("acpr").feature("tnra").set("Cp_mat","userdef");c.physics("acpr").feature("tnra").set("Cp","1005[J/(kg*K)]");c.physics("acpr").feature("tnra").set("gamma_mat","userdef");c.physics("acpr").feature("tnra").set("gamma","1.4");}
 static void run(String label,double target,double len,double ascale,double vscale,int size,int[] src)throws Exception{Model m=ModelUtil.load("m"+label+size,BASE);setup(m,geom(m,target,len,ascale,vscale));MeshSequence q=m.component("comp1").mesh("mesh1");q.feature("size").set("hauto",Integer.toString(size));q.run();m.study("std1").feature("step1").set("plist",String.format(Locale.US,"range(%.0f,2,%.0f)",target-130,target+130));m.result().dataset().create("tcpt","CutPoint3D");m.result().dataset("tcpt").set("pointx",new double[]{0});m.result().dataset("tcpt").set("pointy",new double[]{0});m.result().dataset("tcpt").set("pointz",new double[]{TH/2});m.result().export().create("tdata","Data");m.result().export("tdata").set("data","tcpt");m.result().export("tdata").set("expr",new String[]{"p"});System.out.printf(Locale.US,"AUDIT %s target=%.0f L=%.3f A=%.3f V=%.3f mesh=%d elements=%d src=%s%n",label,target,len*1000,ascale,vscale,size,q.getNumElem(),Arrays.toString(src));for(int s:src){m.param().set("src_state",Integer.toString(s));m.study("std1").run();m.result().export("tdata").set("filename",OUT+label+"_size"+size+"_src"+s+".txt");m.result().export("tdata").run();}m.save(OUT+label+"_size"+size+".mph");ModelUtil.remove("m"+label+size);}
 public static void main(String[] args)throws Exception{ModelUtil.initStandalone(true);int[] all={0,1,2,3};if(args!=null&&args.length>0&&args[0].equals("sentinel")){run("CORNER_LOW_A03",1150,.0092,.98,1.02,1,new int[]{2});run("CORNER_HIGH_A07",750,.0088,1.02,.98,1,new int[]{0});return;}run("SF_LMIN_A05",950,.0088,1,1,3,all);run("SF_LMAX_A05",950,.0092,1,1,3,all);run("SF_AMIN_A05",950,.009,.98,1,3,all);run("SF_AMAX_A05",950,.009,1.02,1,3,all);run("SF_VMIN_A05",950,.009,1,.98,3,all);run("SF_VMAX_A05",950,.009,1,1.02,3,all);double[] fs={1150,1050,950,850,750};String[] as={"A03","A04","A05","A06","A07"};for(int i=0;i<5;i++){run("CORNER_LOW_"+as[i],fs[i],.0092,.98,1.02,2,all);run("CORNER_HIGH_"+as[i],fs[i],.0088,1.02,.98,2,all);}}
}
